// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHh7O28q8C6xhIDKXCL6RzLC1Fq4CSwEk',
    appId: '1:109695533753:web:4f6e8d8743fe9ab7b55168',
    messagingSenderId: '109695533753',
    projectId: 'railway-df4a5',
    authDomain: 'railway-df4a5.firebaseapp.com',
    storageBucket: 'railway-df4a5.firebasestorage.app',
    measurementId: 'G-SZWBE58PB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMvaM9Gts2flRVtXNcd5ChN7QIdzybxbk',
    appId: '1:109695533753:android:88eebe0d6143ed01b55168',
    messagingSenderId: '109695533753',
    projectId: 'railway-df4a5',
    storageBucket: 'railway-df4a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8JM0yuRtXPJC64kvQJD_l0TLQIPxBDEU',
    appId: '1:109695533753:ios:01d9554b4beb89b5b55168',
    messagingSenderId: '109695533753',
    projectId: 'railway-df4a5',
    storageBucket: 'railway-df4a5.firebasestorage.app',
    iosBundleId: 'com.example.flutterRailwayApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8JM0yuRtXPJC64kvQJD_l0TLQIPxBDEU',
    appId: '1:109695533753:ios:01d9554b4beb89b5b55168',
    messagingSenderId: '109695533753',
    projectId: 'railway-df4a5',
    storageBucket: 'railway-df4a5.firebasestorage.app',
    iosBundleId: 'com.example.flutterRailwayApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHh7O28q8C6xhIDKXCL6RzLC1Fq4CSwEk',
    appId: '1:109695533753:web:efaf9dfcc33d3848b55168',
    messagingSenderId: '109695533753',
    projectId: 'railway-df4a5',
    authDomain: 'railway-df4a5.firebaseapp.com',
    storageBucket: 'railway-df4a5.firebasestorage.app',
    measurementId: 'G-08KX9K0MKT',
  );
}
